language: python

python:
  - 3.6

env:
  global:
    # export BITBANK_API_KEY=SET_VALUE_IN_TRAVICE_CI
    # export BITBANK_API_SECRET=SET_VALUE_IN_TRAVICE_CI
    # export LINE_NOTIFY_TOKEN=SET_VALUE_IN_TRAVICE_CI

install:
  - pip install pep8
  - pip install codecov
  - pip install git+https://github.com/bitbankinc/python-bitbankcc.git
  - pip install pandas
  - pip install pytest pytest-cov
  - pip install scikit-learn
  - pip install scipy

script:
  - pep8 src/bitbankAutoOrder.py
#  - pytest src/test_bitbankAutoOrder.py
#  - coverage run src/test_bitbankAutoOrder.py
  - pytest --cov=./src
 
after_success:
  - codecov

notifications:
   slack: keita69sawada:2gXpVEe11Q8bWXIYlTyDxv73