language: python

python:
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install pytest
  - pip install coveralls

#script:
  - pytest bitbankAutoOrder.py
#  - coverage run --source=hoge_test bitbankAutoOrder.py test

after_success:
  - coveralls

#notifications:
#  slack:
#    secure: your_token_key
notifications:
   slack: keita69sawada:2gXpVEe11Q8bWXIYlTyDxv73