language: python

python:
  - 3.5

install:
  - pip install pytest
  - pip install coveralls

#script:
  - pytest src/bitbankAutoOrder.py
  - coverage run --source=src/bitbankAutoOrder.py test_src/test_bitbankAutoOrder.py

after_success:
  - coveralls

notifications:
   slack: keita69sawada:2gXpVEe11Q8bWXIYlTyDxv73